---

- name: copy regtest-miner script
  template:
    src: 'regtest-miner.sh.j2'
    dest: '/usr/local/bin/regtest-miner.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: service_result

- name: create regtest-miner service
  template:
    src: 'regtest-miner.service.j2'
    dest: '/etc/systemd/system/regtest-miner.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: service_result

- name: enable regtest-miner
  systemd:
    name: 'regtest-miner'
    state: restarted
    enabled: True
    masked: False
    daemon_reload: '{{ service_result|changed }}'
